### ISSUE TITLE
BAM MACRO sendMail

### ISSUE THREAD

**Issue by fredo1988** [centreon/centreon-widget-hostgroup-monitoring#19]
[EN]
Hi there,

I think it would be interesting to add a macro that allows to add the name of the PKI in the notification mail.
Because the mail goes back just that busines activity is in error, unspecified.

Thanks in advance.
[EN]

[FR]
Bonjour,

Je pense qu’il serait intéressant d’ajouter une macro qui permette d’ajouter le nom du PKI dans le mail de notification.
Car le mail remonte juste qu’une busines activité est en erreur, sans précision.

Merci par avance.
[FR]

ma version actuelle :
Centreon 2.8.9
Centreon Engine 1.7.2
MariaDB 5.5.53

**Comment by julienmathis** [comment]
Bonjour, 

très bonne idée mais pourquoi ouvrir ce ticket dans le projet du widget hostgroup ?

**Comment by julienmathis** [comment]
Nous avons pris en compte mais nous fermons ce ticket car ce n'est pas le bon endroit :)

**Comment by fredo1988** [comment]
Bonjour,

Je sais jamais où les lettres en faite, je test pour mon entreprise toutes les nouveautés vu qu'on a mis en place vos solutions, je passe beaucoup par des tickets support mais pour les améliorations je fais des tickets perso.

Cordialement.

Frédéric JACQUIN

**Comment by julienmathis** [comment]
Bonjour, 

Il n'y a pas de projet BAM, le mieux pour le moment est de passer par le support ;) Mais nous avons bien pris en compte votre demande.

Merci encore pour votre feedback.

Cordialement,
